import image from './assets/temp.jpg';

export const postList = [
	{
		id: '1',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
	{
		id: '2',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
	{
		id: '3',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
	{
		id: '4',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
	{
		id: '5',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
	{
		id: '6',
		name: 'Aman Tomar',
		location: 'Mumbai',
		likeCount: 0,
		caption: 'this is my great art',
		like: false,
		productName: 'Beautiful Product',
		productPrice: 100,
		productDiscount: 50,
		TotalMRP: 200,
		star: 2,
		image: image,
		DeliveryDate: 'Mon Sept 8',
		SellerName: 'Nikita',
		productDetail:
			'It is a very good product It is a very good product It is a very good product It is a very good product ',
		review: [
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
			{
				name: 'Nikita Ubale',
				comment: 'Good product',
				star: 2,
			},
		],
	},
];
